# runtime: php81

# instance_class: F2

# env_variables:
#   DATABASE_URL: YOUR_DATABASE_URL
#   API_KEY: YOUR_API_KEY

# handlers:
#   - url: /api/.*
#     script: main.app

# automatic_scaling:
#   target_cpu_utilization: 0.65

runtime: nodejs16
service: backend
# env_variables:
#   DATABASE_URL: YOUR_DATABASE_URL
#   API_KEY: YOUR_API_KEY
# ```